{{- if .Values.app.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nano.app.fullname" . }}
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    {{- with .Values.app.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nano.app.selectorLabels" . | nindent 4 }}
{{- end }}
