{{- if and .Values.storage.enabled (not .Values.config.storage.secretRef) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nano.storage.secrets" . }}
  labels:
    {{- include "nano.labels" . | nindent 4 }}
type: Opaque
data:
  rootUser: {{ .Values.config.storage.publicPoolConfiguration.accessKeyId | b64enc | quote }}
  rootPassword: {{ .Values.config.storage.publicPoolConfiguration.secretAccessKey | b64enc | quote }}
{{- end }}
