{{- if and .Values.storage.enabled .Values.storage.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nano.storage.fullname" . }}-data
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.storage.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
  {{- if .Values.storage.persistence.storageClass }}
  {{- if (eq "-" .Values.storage.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.storage.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
