name: nano
services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: nano
      POSTGRES_PASSWORD: nano
      POSTGRES_DB: nano
    ports:
      - "5432:5432"

  # maildev:
  #   image: maildev/maildev:2.1.0
  #   container_name: maildev
  #   ports:
  #     - "1080:1080"
  #     - "1025:1025"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:1080"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8081:8081"

  ollama:
    image: ollama/ollama:0.3.10
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  app:
    image: nano
    build:
      context: .
      tags: [nano:latest]
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NANO_DATABASE_SYNCRONIZE=true
      - NANO_DATABASE_TYPE=postgres
      - NANO_DATABASE_HOST=postgres
      - NANO_DATABASE_PORT=5432
      - NANO_DATABASE_USERNAME=nano
      - NANO_DATABASE_PASSWORD=nano
      - NANO_DATABASE_DATABASE=nano
    ports:
      - "3000:3000"
