name: nano-ce

volumes:
  ollama:
    driver: local
  pgadmin:
    driver: local
  postgres:
    driver: local

services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  postgres:
    image: postgres
    container_name: nano-ce-postgres
    environment:
      POSTGRES_USER: nano
      POSTGRES_PASSWORD: nano
      POSTGRES_DB: nano
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    volumes:
      - pgadmin:/pgadmin4

  # maildev:
  #   image: maildev/maildev:2.1.0
  #   container_name: maildev
  #   ports:
  #     - "1080:1080"
  #     - "1025:1025"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:1080"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  # ollama:
  #   image: ollama/ollama:0.3.10
  #   container_name: ollama
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama:/root/.ollama

  # chroma:
  #   image: chromadb/chroma:latest
  #   container_name: chroma
  #   ports:
  #     - "8081:8081"

  app:
    image: nano-ce
    container_name: nano-ce-app
    command:
      - app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0

  api:
    image: nano-ce
    container_name: nano-ce-api
    command:
      - api
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - NODE_ENV=production
      - DATABASE_SYNCRONIZE=true
      - DATABASE_URL=postgres://nano:nano@postgres:5432/nano
      - USER_TRUST_PROXY=true
      - USER_SECRET_KEY=your_secret_key_here
      - USER_CYPHER_ALGORITHM=aes-256-gcm
      - VAULT_DEFAULT_LOCAL_SECRET_KEY=your_local_secret_key_here
      - VAULT_CONFIGURATION_SECRET_KEY=your_configuration_secret_key_here

  runner:
    image: nano-ce
    container_name: nano-ce-runner
    command:
      - runner
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
      - HOST=0.0.0.0