name: nano

volumes:
  postgres:
    driver: local

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: nano
      POSTGRES_PASSWORD: nano
      POSTGRES_DB: nano
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  # maildev:
  #   image: maildev/maildev:2.1.0
  #   container_name: maildev
  #   ports:
  #     - "1080:1080"
  #     - "1025:1025"

  # ollama:
  #   image: ollama/ollama:0.3.10
  #   container_name: ollama
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama:/root/.ollama

  app:
    image: nwrx/nano
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NUXT_PUBLIC_API_URL=http://localhost:3001
      - NUXT_PUBLIC_APP_URL=http://localhost:3000

  api:
    image: nwrx/nano
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - api
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - APP_URL=http://localhost:3000
      - DATABASE_SYNCRONIZE=true
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=nano
      - DATABASE_USERNAME=nano
      - DATABASE_PASSWORD=nano
      - USER_TRUST_PROXY=true
      - USER_SECRET_KEY=your_secret_key_here
      - USER_CYPHER_ALGORITHM=aes-256-gcm
      - VAULT_DEFAULT_LOCAL_SECRET_KEY=your_local_secret_key_here
      - VAULT_CONFIGURATION_SECRET_KEY=your_configuration_secret_key_here

  runner-1:
    image: nwrx/nano
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - runner
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
      - HOST=0.0.0.0
      - RUNNER_NAME=nano-runner-1

  runner-2:
    image: nwrx/nano
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - runner
    ports:
      - "3011:3011"
    environment:
      - PORT=3011
      - HOST=0.0.0.0
      - RUNNER_NAME=nano-runner-2

  runner-3:
    image: nwrx/nano
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - runner
    ports:
      - "3012:3012"
    environment:
      - PORT=3012
      - HOST=0.0.0.0
      - RUNNER_NAME=nano-runner-3
