name: nano
services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: nano
      POSTGRES_PASSWORD: nano
      POSTGRES_DB: nano
    ports:
      - "5432:5432"

  app:
    image: nano-app
    build:
      context: .
      target: nano-app
      tags: 
        - nano-app:latest
    depends_on:
      - api
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    ports:
      - "3000:3000"

  api:
    image: nano-api
    build:
      context: .
      target: nano-api
      tags: 
        - nano-api:latest
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - NANO_DATABASE_SYNCRONIZE=true

      # - NANO_DATABASE_TYPE=sqlite
      # - NANO_DATABASE_DATABASE=.data/database.sqlite

      - NANO_DATABASE_TYPE=postgres
      - NANO_DATABASE_HOST=postgres
      - NANO_DATABASE_PORT=5432
      - NANO_DATABASE_USERNAME=nano
      - NANO_DATABASE_PASSWORD=nano
      - NANO_DATABASE_DATABASE=nano
    ports:
      - "3001:3001"
