name: nano
services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: nano
      POSTGRES_PASSWORD: nano
      POSTGRES_DB: nano
    ports:
      - "5432:5432"

  app:
    image: nano
    build:
      context: .
      tags: [nano:latest]
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NANO_DATABASE_SYNCRONIZE=true
      - NANO_DATABASE_TYPE=postgres
      - NANO_DATABASE_HOST=postgres
      - NANO_DATABASE_PORT=5432
      - NANO_DATABASE_USERNAME=nano
      - NANO_DATABASE_PASSWORD=nano
      - NANO_DATABASE_DATABASE=nano
    ports:
      - "3000:3000"
