{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nano.database.fullname" . }}
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    {{- with .Values.database.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.database.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "nano.database.selectorLabels" . | nindent 4 }}
{{- end }}
