{{- if .Values.database.enabled }}
{{- if .Values.database.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nano.database.fullname" . }}-data
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    {{- toYaml .Values.database.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
  {{- if .Values.database.persistence.storageClass }}
  {{- if (eq "-" .Values.database.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.database.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
