{{- if and .Values.api.enabled (not .Values.config.api.secretRef) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nano.api.secrets" . }}
  labels:
    {{- include "nano.labels" . | nindent 4 }}
type: Opaque
data:
  NANO_APP_URL: {{ .Values.config.appUrl | b64enc | quote }}
  NANO_TRUST_PROXY: {{ .Values.config.api.trustProxy | toString | b64enc | quote }}
  NANO_SESSION_DURATION: {{ .Values.config.api.sessionDuration | b64enc | quote }}
  NANO_SESSION_ID_COOKIE_NAME: {{ .Values.config.api.sessionIdCookieName | b64enc | quote }}
  NANO_SESSION_TOKEN_COOKIE_NAME: {{ .Values.config.api.sessionTokenCookieName | b64enc | quote }}
  NANO_SESSION_ENCRYPTION_SECRET: {{ .Values.config.api.sessionEncryptionSecret | b64enc | quote }}
  NANO_SESSION_ENCRYPTION_ALGORITHM: {{ .Values.config.api.sessionEncryptionAlgorithm | b64enc | quote }}
  NANO_USER_RECOVERY_TOKEN_DURATION: {{ .Values.config.api.userRecoveryTokenDuration | b64enc | quote }}
  NANO_VAULT_ENCRYPTION_SECRET: {{ .Values.config.api.vaultEncryptionSecret | b64enc | quote }}
  NANO_VAULT_ENCRYPTION_ALGORITHM: {{ .Values.config.api.vaultEncryptionAlgorithm | b64enc | quote }}
  NANO_STORAGE_ENCRYPTION_SECRET: {{ .Values.config.storage.encryptionSecret | b64enc | quote }}
  NANO_STORAGE_ENCRYPTION_ALGORITHM: {{ .Values.config.storage.encryptionAlgorithm | b64enc | quote }}
  NANO_STORAGE_PUBLIC_POOL_TYPE: {{ .Values.config.storage.publicPoolType | b64enc | quote }}
  NANO_STORAGE_PUBLIC_POOL_CONFIGURATION: {{ include "nano.storage.poolConfiguration" . | b64enc | quote }}
  NANO_STORAGE_PUBLIC_DOWNLOAD_URL: {{ .Values.config.storage.publicDownloadUrl | b64enc | quote }}
  NANO_ICON_CDN_URL: {{ .Values.config.api.iconCdnUrl | b64enc | quote }}
  NANO_ICONIFY_URL: {{ .Values.config.api.iconifyUrl | b64enc | quote }}
{{- end }}
