{{- if .Values.api.enabled -}}
{{- if .Values.api.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nano.api.fullname" . }}-storage
  labels:
    {{- include "nano.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.api.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size }}
  {{- if .Values.api.persistence.storageClass }}
  {{- if (eq "-" .Values.api.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.api.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
