{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nano.fullname" . }}-api
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- with .Values.api.autoscaling }}
  {{- if not .enabled }}
  replicas: {{ $.Values.api.replicas }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nano.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nano.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nano.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "nano.image" . }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ['sh', '-c']
          args:
            - |
              {{- if and .Values.api.config.initialRunnersEnabled .Values.runners }}
              # Expand shell variables in INITIAL_RUNNERS using eval
              export INITIAL_RUNNERS=$(eval echo \"$INITIAL_RUNNERS\")
              {{- end }}
              exec nano api
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "nano.fullname" . }}-api-secret
            {{- if .Values.runners }}
            - secretRef:
                name: {{ include "nano.fullname" . }}-runner-tokens
            {{- end }}
          env:
            - name: PORT
              value: {{ .Values.api.port | quote }}
            - name: HOST
              value: {{ .Values.api.config.host | quote }}
            - name: APP_URL
              value: {{ .Values.api.config.appUrl | quote }}
            - name: USER_TRUST_PROXY
              value: {{ .Values.api.config.userTrustProxy | quote }}
            - name: USER_SESSION_ID_COOKIE_NAME
              value: {{ .Values.api.config.userSessionIdCookieName | quote }}
            - name: USER_SESSION_TOKEN_COOKIE_NAME
              value: {{ .Values.api.config.userSessionTokenCookieName | quote }}
            - name: USER_SESSION_DURATION
              value: {{ .Values.api.config.userSessionDuration | quote }}
            - name: USER_RECOVERY_DURATION
              value: {{ .Values.api.config.userRecoveryDuration | quote }}
            - name: VAULT_CONFIGURATION_ALGORITHM
              value: {{ .Values.api.config.vaultConfigurationAlgorithm | quote }}
            - name: ICON_CDN_URL
              value: {{ .Values.api.config.iconCdnUrl | quote }}
            - name: ICON_ICONIFY_URL
              value: {{ .Values.api.config.iconIconifyUrl | quote }}
            - name: DATABASE_TYPE
              value: {{ include "nano.database.type" . | quote }}
            {{- if eq (include "nano.database.type" .) "sqlite" }}
            - name: DATABASE_PATH
              value: "/data/database/nano.db"
            {{- end }}
            - name: DATABASE_SYNCRONIZE
              value: {{ .Values.database.synchronize | toString | quote }}
            {{- if eq (include "nano.database.type" .) "postgres" }}
            {{- if eq .Values.database.postgres.mode "url" }}
            - name: DATABASE_URL
              value: {{ .Values.database.postgres.url | quote }}
            {{- else }}
            - name: DATABASE_HOST
              value: {{ .Values.database.postgres.host | quote }}
            - name: DATABASE_PORT
              value: {{ .Values.database.postgres.port | toString | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.database.postgres.database | quote }}
            {{- end }}
            {{- end }}
            {{- if and .Values.api.config.initialRunnersEnabled .Values.runners }}
            - name: INITIAL_RUNNERS
              value: {{ include "nano.initialRunners" . | quote }}
            {{- end }}
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: storage
              mountPath: /data/storage
            - name: database
              mountPath: /data/database
      volumes:
        - name: tmp
          emptyDir: {}
        # Storage volume - controlled by api.persistence.enabled
        {{- if .Values.api.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "nano.fullname" . }}-storage
        {{- else }}
        - name: storage
          emptyDir: {}
        {{- end }}
        # Database volume - controlled by database.sqlite.persistence.enabled (for SQLite only)
        {{- if and (eq (include "nano.database.type" .) "sqlite") .Values.database.sqlite.persistence.enabled }}
        - name: database
          persistentVolumeClaim:
            claimName: {{ include "nano.fullname" . }}-database
        {{- else }}
        - name: database
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}