{{- if .Values.app.enabled }}
{{- if .Values.app.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nano.fullname" . }}-app
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  minAvailable: {{ .Values.app.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "nano.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
{{- end }}
---
{{- if .Values.api.enabled }}
{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nano.fullname" . }}-api
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "nano.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
{{- end }}
---