{{- if and .Values.api.enabled .Values.api.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nano.fullname" . }}-api-storage
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    {{- range .Values.api.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size | quote }}
  {{- if .Values.api.persistence.storageClass }}
  {{- if (eq "-" .Values.api.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.api.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
