{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nano.fullname" . }}-api-secret
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
  {{- if eq (include "nano.database.type" .) "postgres" }}
  {{- if eq .Values.database.postgres.mode "params" }}
  # PostgreSQL database credentials (sensitive)
  DATABASE_USERNAME: {{ .Values.database.postgres.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.database.postgres.password | b64enc }}
  {{- else if eq .Values.database.postgres.mode "url" }}
  # PostgreSQL database URL (sensitive)
  DATABASE_URL: {{ .Values.database.postgres.url | b64enc }}
  {{- end }}
  {{- end }}
  # Application secrets
  USER_SECRET_KEY: {{ .Values.api.config.userSecretKey | b64enc }}
  USER_CYPHER_ALGORITHM: {{ .Values.api.config.userCypherAlgorithm | b64enc }}
  VAULT_DEFAULT_LOCAL_SECRET_KEY: {{ .Values.api.config.vaultDefaultLocalSecretKey | b64enc }}
  VAULT_CONFIGURATION_SECRET_KEY: {{ .Values.api.config.vaultConfigurationSecretKey | b64enc }}
{{- end }}
---
{{- if .Values.runners }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nano.fullname" . }}-runner-tokens
  labels:
    {{- include "nano.labels" . | nindent 4 }}
    app.kubernetes.io/component: runner
type: Opaque
data:
  {{- range .Values.runners }}
  {{- if .enabled }}
  {{- $runner := . }}
  {{- $root := $ }}
  {{- $runnerName := include "nano.runner.name" (dict "runner" $runner "root" $root) }}
  {{- range $i := until (.instances | int) }}
  {{ $runnerName | upper | replace "-" "_" }}_{{ $i }}: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}