{{- range .Values.runners }}
{{- if .enabled }}
{{- $runner := . }}
{{- $root := $ }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nano.runner.name" (dict "runner" $runner "root" $root) }}
  labels:
    {{- include "nano.runner.labels" (dict "runner" $runner "root" $root) | nindent 4 }}
spec:
  type: {{ $runner.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $runner.service.port | default 80 }}
      targetPort: {{ $runner.port | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "nano.runner.selectorLabels" (dict "runner" $runner "root" $root) | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nano.runner.name" (dict "runner" $runner "root" $root) }}-headless
  labels:
    {{- include "nano.runner.labels" (dict "runner" $runner "root" $root) | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ $runner.port | default 8080 }}
      targetPort: {{ $runner.port | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "nano.runner.selectorLabels" (dict "runner" $runner "root" $root) | nindent 4 }}
{{- end }}
{{- end }}
