{{- if .Values.runners.enabled -}}
{{- if .Values.runners.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nano.runners.fullname" . }}-netpol
  labels:
    {{- include "nano.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nano.runners.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "nano.api.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
{{- end }}
{{- end }}
