export const MODULES_MOCK = [
  {
    categories: ['Communication', 'Productivity'],
    industries: ['Technology', 'Business', 'Education'],
    title: 'Slack',
    description: 'Integrate your Slack workspace for seamless collaboration and communication within teams, enabling automated interactions with channels and messages to enhance productivity.',
    maintainer: 'Slack Technologies',
    icon: 'i-logos:slack-icon',
    rating: 4.5,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['Productivity', 'Version Control'],
    industries: ['Technology', 'Software Development'],
    title: 'GitHub',
    description: 'Connect your GitHub repositories to facilitate robust integrations for managing issues and pull requests, streamlining workflows for development teams.',
    maintainer: 'GitHub Inc.',
    icon: 'i-logos:github-icon',
    rating: 4.8,
    ratingCount: 321,
    isOfficial: true,
  },
  {
    categories: ['Productivity', 'Cloud Storage'],
    industries: ['Technology', 'Business', 'Education'],
    title: 'Google Drive',
    description: 'Integrate with Google Drive to manage files and folders seamlessly, allowing for efficient file sharing and collaboration in real time.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-drive',
    rating: 4.2,
    ratingCount: 213,
    isOfficial: true,
  },
  {
    categories: ['Social Media', 'Communication'],
    industries: ['Media', 'Marketing'],
    title: 'Twitter / X',
    description: 'Connect your Twitter account to automate interactions with tweets and mentions, enhancing engagement and content distribution strategies.',
    maintainer: 'Twitter Inc.',
    icon: 'i-logos:x',
    rating: 4.6,
    ratingCount: 432,
    isOfficial: true,
  },
  {
    categories: ['Utilities', 'Development'],
    industries: ['Technology'],
    title: 'Core utilities',
    description: 'A comprehensive suite of core utilities designed to assist in the construction and management of integrations, providing essential tools for developers.',
    maintainer: 'Nanoworks',
    icon: 'i-carbon:flow',
    rating: 4.9,
    ratingCount: 123,
    isCurated: true,
  },
  {
    categories: ['Communication', 'Productivity'],
    industries: ['Technology', 'Business'],
    title: 'Microsoft Teams',
    description: 'Integrate Microsoft Teams to enable automated interactions with your channels and messages, improving collaboration and team productivity.',
    maintainer: 'Microsoft Corporation',
    icon: 'i-logos:microsoft-teams',
    rating: 4.7,
    ratingCount: 321,
    isOfficial: true,
  },
  {
    categories: ['Productivity', 'Calendar'],
    industries: ['Technology', 'Business', 'Education'],
    title: 'Google Calendar',
    description: 'Connect your Google Calendar for deep integration with events and reminders, facilitating better time management and scheduling automation.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-calendar',
    rating: 4.3,
    ratingCount: 213,
    isOfficial: true,
  },
  {
    categories: ['Project Management', 'Productivity'],
    industries: ['Technology', 'Business'],
    title: 'Trello',
    description: 'Integrate Trello to manage boards and cards effectively, streamlining project management processes through automation and collaboration tools.',
    maintainer: 'Atlassian Corporation',
    icon: 'i-logos:trello',
    rating: 4.5,
    ratingCount: 432,
    isOfficial: true,
  },
  {
    categories: ['Productivity', 'Spreadsheet'],
    industries: ['Technology', 'Business', 'Education'],
    title: 'Google Sheets',
    description: 'Connect your Google Sheets for powerful integrations that enhance data manipulation and collaboration within spreadsheets and cells.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-sheets',
    rating: 4.6,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['Analytics', 'Business Intelligence'],
    industries: ['Technology', 'Business'],
    title: 'Google Analytics',
    description: 'Integrate Google Analytics to access and analyze your reports and metrics, enhancing data-driven decision-making processes.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-analytics',
    rating: 4.8,
    ratingCount: 321,
    isOfficial: true,
  },
  {
    categories: ['Mapping', 'Geolocation'],
    industries: ['Technology', 'Transportation', 'Travel'],
    title: 'Google Maps',
    description: 'Integrate Google Maps to automate interactions with locations and routes, enhancing geolocation capabilities in your applications.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-maps',
    rating: 4.4,
    ratingCount: 213,
    isOfficial: true,
  },
  {
    categories: ['Cloud Computing', 'Infrastructure'],
    industries: ['Technology', 'Business'],
    title: 'Google Cloud',
    description: 'Connect your Google Cloud account for deep integrations with services and resources, facilitating cloud management and orchestration.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-cloud',
    rating: 4.7,
    ratingCount: 432,
    isOfficial: true,
  },
  {
    categories: ['Search', 'Analytics'],
    industries: ['Technology', 'Business'],
    title: 'Google Search',
    description: 'Integrate Google Search to automate queries and results management, enhancing search capabilities in your applications.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-icon',
    rating: 4.2,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['Photo Management', 'Cloud Storage'],
    industries: ['Technology', 'Media'],
    title: 'Google Photos',
    description: 'Connect your Google Photos for deep integrations with albums and pictures, enhancing media management and sharing capabilities.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-photos',
    rating: 4.5,
    ratingCount: 321,
    isOfficial: true,
  },
  // Business Intelligence
  {
    categories: ['Data Management', 'Business Intelligence'],
    industries: ['Technology', 'Business'],
    title: 'Google BigQuery',
    description: 'Connect your Google BigQuery account to integrate and analyze large datasets, streamlining data-driven insights and reporting.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-bigquery',
    rating: 4.6,
    ratingCount: 213,
    isOfficial: true,
  },
  {
    categories: ['Reporting', 'Data Visualization'],
    industries: ['Technology', 'Business'],
    title: 'Google Data Studio',
    description: 'Integrate Google Data Studio to create comprehensive reports and dashboards, enhancing data visualization and business intelligence capabilities.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-data-studio',
    rating: 4.8,
    ratingCount: 432,
    isOfficial: true,
  },
  {
    categories: ['Tag Management', 'Analytics'],
    industries: ['Technology', 'Marketing'],
    title: 'Google Tag Manager',
    description: 'Connect Google Tag Manager for automated tag and trigger management, facilitating better tracking and analytics implementations.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-tag-manager',
    rating: 4.7,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['A/B Testing', 'Analytics'],
    industries: ['Technology', 'Marketing'],
    title: 'Google Optimize',
    description: 'Integrate Google Optimize to manage experiments and variants effectively, enhancing user experience through data-driven optimization.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-optimize',
    rating: 4.9,
    ratingCount: 321,
    isOfficial: true,
  },
  {
    categories: ['Advertising', 'Monetization'],
    industries: ['Technology', 'Marketing'],
    title: 'Google AdSense',
    description: 'Connect your Google AdSense account to manage ads and earnings, facilitating effective monetization strategies for online content.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-adsense',
    rating: 4.2,
    ratingCount: 213,
    isOfficial: true,
  },
  {
    categories: ['Advertising', 'Campaign Management'],
    industries: ['Technology', 'Marketing'],
    title: 'Google AdWords',
    description: 'Integrate your Google AdWords account for managing campaigns and keywords effectively, enhancing online advertising efforts.',
    maintainer: 'Google LLC',
    icon: 'i-logos:google-adwords',
    rating: 4.5,
    ratingCount: 432,
    isOfficial: true,
  },
  // Business Intelligence (Other than Google)
  {
    categories: ['Advertising', 'Business Intelligence'],
    industries: ['Technology', 'Marketing'],
    title: 'Facebook Business',
    description: 'Connect your Facebook Business account to integrate ads and insights, streamlining social media marketing strategies.',
    maintainer: 'Facebook Inc.',
    icon: 'i-logos:facebook-business',
    rating: 4.6,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['Advertising', 'Campaign Management'],
    industries: ['Technology', 'Marketing'],
    title: 'Facebook Ads',
    description: 'Integrate your Facebook Ads account for comprehensive management of campaigns and ad sets, enhancing targeted advertising.',
    maintainer: 'Facebook Inc.',
    icon: 'i-logos:facebook-ads',
    rating: 4.8,
    ratingCount: 321,
    isOfficial: true,
  },
  {
    categories: ['Analytics', 'Tracking'],
    industries: ['Technology', 'Marketing'],
    title: 'Facebook Pixel',
    description: 'Connect your Facebook Pixel account to automate tracking of events and conversions, enhancing advertising effectiveness.',
    maintainer: 'Facebook Inc.',
    icon: 'i-logos:facebook-pixel',
    rating: 4.7,
    ratingCount: 213,
    isOfficial: true,
  },
  {
    categories: ['Analytics', 'Insights'],
    industries: ['Technology', 'Marketing'],
    title: 'Facebook Insights',
    description: 'Integrate your Facebook Insights account for detailed analysis of your page and posts, informing content strategies.',
    maintainer: 'Facebook Inc.',
    icon: 'i-logos:facebook-insights',
    rating: 4.9,
    ratingCount: 432,
    isOfficial: true,
  },
  {
    categories: ['Audience Management', 'Marketing'],
    industries: ['Technology', 'Marketing'],
    title: 'Facebook Audience',
    description: 'Connect your Facebook Audience account to manage segments and lists effectively, enhancing audience targeting for campaigns.',
    maintainer: 'Facebook Inc.',
    icon: 'i-logos:facebook-audience',
    rating: 4.2,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['Event Management', 'Marketing'],
    industries: ['Technology', 'Marketing'],
    title: 'Facebook Events',
    description: 'Integrate your Facebook Events account for managing events and RSVPs, enhancing engagement strategies for audience participation.',
    maintainer: 'Facebook Inc.',
    icon: 'i-logos:facebook-events',
    rating: 4.5,
    ratingCount: 321,
    isOfficial: true,
  },
  {
    categories: ['Page Management', 'Marketing'],
    industries: ['Technology', 'Marketing'],
    title: 'Facebook Pages',
    description: 'Connect your Facebook Pages account to automate interactions with your page and posts, improving audience engagement and content distribution.',
    maintainer: 'Facebook Inc.',
    icon: 'i-logos:facebook',
    rating: 4.6,
    ratingCount: 213,
    isOfficial: true,
  },
  // DevOps
  {
    categories: ['Continuous Integration', 'DevOps'],
    industries: ['Technology', 'Software Development'],
    title: 'GitHub Actions',
    description: 'Connect your GitHub Actions account for automating workflows and jobs, enhancing CI/CD processes and development efficiency.',
    maintainer: 'GitHub Inc.',
    icon: 'i-logos:github-actions',
    rating: 4.8,
    ratingCount: 432,
    isOfficial: true,
  },
  {
    categories: ['Continuous Integration', 'DevOps'],
    industries: ['Technology', 'Software Development'],
    title: 'GitLab CI/CD',
    description: 'Integrate GitLab CI/CD to automate your pipelines and jobs, streamlining continuous integration and delivery workflows.',
    maintainer: 'GitLab Inc.',
    icon: 'i-logos:gitlab',
    rating: 4.7,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['Continuous Integration', 'DevOps'],
    industries: ['Technology', 'Software Development'],
    title: 'Jenkins',
    description: 'Connect your Jenkins account to automate jobs and builds, providing a robust solution for CI/CD pipeline management.',
    maintainer: 'Jenkins Foundation',
    icon: 'i-logos:jenkins',
    rating: 4.9,
    ratingCount: 321,
    isOfficial: true,
  },
  {
    categories: ['Continuous Integration', 'DevOps'],
    industries: ['Technology', 'Software Development'],
    title: 'Travis CI',
    description: 'Integrate Travis CI for automated builds and logs, enhancing continuous integration processes for software development.',
    maintainer: 'Travis CI Inc.',
    icon: 'i-logos:travis-ci',
    rating: 4.2,
    ratingCount: 213,
    isOfficial: true,
  },
  {
    categories: ['Continuous Integration', 'DevOps'],
    industries: ['Technology', 'Software Development'],
    title: 'CircleCI',
    description: 'Connect your CircleCI account to streamline your pipelines and workflows, improving the efficiency of CI/CD processes.',
    maintainer: 'CircleCI Inc.',
    icon: 'i-logos:circleci',
    rating: 4.5,
    ratingCount: 432,
    isOfficial: true,
  },
  {
    categories: ['Continuous Integration', 'DevOps'],
    industries: ['Technology', 'Software Development'],
    title: 'Bitbucket Pipelines',
    description: 'Integrate Bitbucket Pipelines for automated management of pipelines and builds, facilitating streamlined development workflows.',
    maintainer: 'Atlassian Corporation',
    icon: 'i-logos:bitbucket',
    rating: 4.6,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['Continuous Integration', 'DevOps'],
    industries: ['Technology', 'Software Development'],
    title: 'Azure DevOps',
    description: 'Connect your Azure DevOps account to automate your pipelines and builds, enhancing collaboration and productivity in software development.',
    maintainer: 'Microsoft Corporation',
    icon: 'i-logos:azure-icon',
    rating: 4,
    ratingCount: 321,
    isOfficial: true,
  },
  // News & Media
  {
    categories: ['News', 'Media'],
    industries: ['Media', 'Publishing'],
    title: 'New York Times',
    description: 'Connect your New York Times account to automate interactions with your articles and sections, enhancing content delivery and accessibility.',
    maintainer: 'The New York Times Company',
    icon: '',
    rating: 4.8,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['News', 'Media'],
    industries: ['Media', 'Publishing'],
    title: 'The Guardian',
    description: 'Integrate your The Guardian account for seamless access to articles and sections, improving news delivery and reader engagement.',
    maintainer: 'Guardian News & Media Limited',
    icon: 'https://i.pinimg.com/736x/3e/ab/ae/3eabae6b843c200be67840755b34a19c.jpg',
    rating: 4.9,
    ratingCount: 321,
    isOfficial: true,
  },
  {
    categories: ['News', 'Media'],
    industries: ['Media', 'Broadcasting'],
    title: 'BBC News',
    description: 'Connect your BBC News account to enable deep integrations with your articles and sections, enhancing content accessibility and engagement.',
    maintainer: 'British Broadcasting Corporation',
    icon: 'i-logos:bbc-news',
    rating: 4.7,
    ratingCount: 213,
    isOfficial: true,
  },
  {
    categories: ['News', 'Media'],
    industries: ['Media', 'Broadcasting'],
    title: 'CNN',
    description: 'Integrate your CNN account for real-time access to articles and sections, enhancing news distribution and audience engagement.',
    maintainer: 'Cable News Network',
    icon: 'i-logos:cnn',
    rating: 4.6,
    ratingCount: 432,
    isOfficial: true,
  },
  {
    categories: ['News', 'Media'],
    industries: ['Media', 'Broadcasting'],
    title: 'Fox News',
    description: 'Connect your Fox News account for automated interactions with articles and sections, improving audience engagement with news content.',
    maintainer: 'Fox News Network LLC',
    icon: 'i-logos:fox-news',
    rating: 4.5,
    ratingCount: 123,
    isOfficial: true,
  },
  {
    categories: ['News', 'Media'],
    industries: ['Media', 'Broadcasting'],
    title: 'Al Jazeera',
    description: 'Integrate your Al Jazeera account for seamless access to articles and sections, enhancing global news delivery and engagement.',
    maintainer: 'Al Jazeera Media Network',
    icon: 'i-logos:al-jazeera',
    rating: 4.4,
    ratingCount: 321,
    isOfficial: true,
  },
  {
    categories: ['News', 'Media'],
    industries: ['Media', 'Publishing'],
    title: 'The Washington Post',
    description: 'Connect your The Washington Post account for automated interactions with articles and sections, improving access to news content.',
    maintainer: 'Nash Holdings LLC',
    icon: 'i-logos:washington-post',
    rating: 4,
  },
]
