name: CI
permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  ci:
    name: Continuous Integration & Deployment to Private Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata from GitHub event
        id: meta-app
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/nwrx/nano-app
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Extract Docker metadata from GitHub event
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/nwrx/nano-api
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push nano-app
        uses: docker/build-push-action@v6
        with:
          target: nano-app
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}

      - name: Build and push nano-api
        uses: docker/build-push-action@v6
        with:
          target: nano-api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

